// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gndhnoijwexuuayvxwom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZGhub2lqd2V4dXVheXZ4d29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzU4NTUsImV4cCI6MjA2NTk1MTg1NX0.rOuiEISzdVlvJvuKm_326YG3Lcl6-mUclcfwSsBDNrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);